import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        { type: 'doc', id: 'intro' },
        {
            type: 'category',
            label: 'Guias',
            collapsible: true,
            collapsed: false,
            items: [{ type: 'autogenerated', dirName: 'guides' }],
        },
        {
            type: 'category',
            label: 'API Reference',
            collapsible: true,
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'api' }],
        },
    ],
};

export default sidebars;
